In [5]:
# conn.close()

In [1]:
import psycopg2
import pandas as pd

In [2]:
DBNAME = "opportunity_youth"

In [3]:
conn = psycopg2.connect(dbname=DBNAME)

In [4]:
pd.read_sql("SELECT * FROM pums_2017 LIMIT 100;", conn)

,rt,serialno,division,sporder,puma,region,st,adjinc,pwgtp,agep,...,pwgtp71,pwgtp72,pwgtp73,pwgtp74,pwgtp75,pwgtp76,pwgtp77,pwgtp78,pwgtp79,pwgtp80
0,P,2013000000006,9,01,11606,4,53,1061971,27.0,68.0,...,53.0,24.0,39.0,24.0,7.0,27.0,8.0,46.0,25.0,50.0
1,P,2013000000006,9,02,11606,4,53,1061971,22.0,66.0,...,49.0,21.0,38.0,20.0,7.0,25.0,8.0,41.0,22.0,47.0
2,P,2013000000012,9,01,10100,4,53,1061971,22.0,72.0,...,24.0,22.0,25.0,7.0,21.0,35.0,6.0,22.0,6.0,37.0
3,P,2013000000012,9,02,10100,4,53,1061971,19.0,64.0,...,21.0,18.0,19.0,7.0,17.0,29.0,6.0,19.0,6.0,29.0
4,P,2013000000038,9,01,11505,4,53,1061971,4.0,52.0,...,4.0,1.0,2.0,8.0,8.0,1.0,4.0,6.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,P,2013000001691,9,01,11602,4,53,1061971,8.0,52.0,...,3.0,8.0,12.0,2.0,3.0,7.0,8.0,13.0,8.0,7.0
96,P,2013000001691,9,02,11602,4,53,1061971,8.0,59.0,...,2.0,7.0,14.0,3.0,2.0,8.0,7.0,13.0,7.0,8.0
97,P,2013000001691,9,03,11602,4,53,1061971,8.0,14.0,...,2.0,8.0,11.0,2.0,2.0,8.0,7.0,13.0,8.0,8.0
98,P,2013000001693,9,01,11616,4,53,1061971,14.0,61.0,...,16.0,4.0,13.0,15.0,15.0,4.0,21.0,25.0,23.0,15.0
99,P,2013000001693,9,02,11616,4,53,1061971,21.0,25.0,...,21.0,5.0,19.0,18.0,23.0,6.0,29.0,35.0,25.0,24.0

In [6]:
#get table schema using postgresql/psycopg2 syntax
QUERY = """
SELECT table_schema, table_name
FROM information_schema.tables
WHERE (table_schema = 'public')
ORDER BY table_schema, table_name;
"""

table_info = pd.read_sql(QUERY, conn)
table_names = table_info['table_name']
table_names
for table in table_names:
    print(table)

ct_puma_xwalk
puma_names_2010
pums_2017
wa_geo_xwalk
wa_jobs_2017

In [7]:
#find table contents/keys 
for table in table_names:
    QUERY = f"""
        SELECT *
        FROM  {table}
        WHERE false
        """
    
    print("".join(['\033[1m', f'{table}', '\033[0m']))#make column name bold
    print(pd.read_sql(QUERY, conn))

ct_puma_xwalk
Empty DataFrame
Columns: [statefp, countyfp, tractce, puma5ce]
Index: []
puma_names_2010
Empty DataFrame
Columns: [state_fips, state_name, cpuma0010, puma, geoid, gisjoin, puma_name]
Index: []
pums_2017
Empty DataFrame
Columns: [rt, serialno, division, sporder, puma, region, st, adjinc, pwgtp, agep, cit, citwp, cow, ddrs, dear, deye, dout, dphy, drat, dratx, drem, eng, fer, gcl, gcm, gcr, hins1, hins2, hins3, hins4, hins5, hins6, hins7, intp, jwmnp, jwrip, jwtr, lanx, mar, marhd, marhm, marht, marhw, marhyp, mig, mil, mlpa, mlpb, mlpcd, mlpe, mlpfg, mlph, mlpi, mlpj, mlpk, nwab, nwav, nwla, nwlk, nwre, oip, pap, relp, retp, sch, schg, schl, semp, sex, ssip, ssp, wagp, wkhp, wkl, wkw, wrk, yoep, anc, anc1p, anc2p, decade, dis, drivesp, esp, esr, fod1p, fod2p, hicov, hisp, indp, jwap, jwdp, lanp, migpuma, migsp, msp, naicsp, nativity, nop, oc, ...]
Index: []

[0 rows x 286 columns]
wa_geo_xwalk
Empty DataFrame
Columns: [tabblk2010, st, stusps, stname, cty, ctyname, trct, trctname, bgrp, bgrpname, cbsa, cbsaname, zcta, zctaname, stplc, stplcname, ctycsub, ctycsubname, stcd116, stcd116name, stsldl, stsldlname, stsldu, stslduname, stschool, stschoolname, stsecon, dtseconname, trib, tribname, tsub, tsubname, stanrc, stanrcname, necta, nectname, mil, milname, stwib, stwibname, blklatdd, blklondd, createdate]
Index: []

[0 rows x 43 columns]
wa_jobs_2017
Empty DataFrame
Columns: [w_geocode, c000, ca01, ca02, ca03, ce01, ce02, ce03, cns01, cns02, cns03, cns04, cns05, cns06, cns07, cns08, cns09, cns10, cns11, cns12, cns13, cns14, cns15, cns16, cns17, cns18, cns19, cns20, cr01, cr02, cr03, cr04, cr05, cr07, ct01, ct02, cd01, cd02, cd03, cd04, cs01, cs02, cfa01, cfa02, cfa03, cfa04, cfa05, cfs01, cfs02, cfs03, cfs04, cfs05, createdate]
Index: []

[0 rows x 53 columns]

In [8]:
#find table columns/keys of pums_2017

QUERY = """
    SELECT *
    FROM pums_2017
    WHERE false
    """
    
print("".join(['\033[1m', 'pums_2017', '\033[0m']))#make column name bold
print(pd.read_sql(QUERY, conn))

pums_2017
Empty DataFrame
Columns: [rt, serialno, division, sporder, puma, region, st, adjinc, pwgtp, agep, cit, citwp, cow, ddrs, dear, deye, dout, dphy, drat, dratx, drem, eng, fer, gcl, gcm, gcr, hins1, hins2, hins3, hins4, hins5, hins6, hins7, intp, jwmnp, jwrip, jwtr, lanx, mar, marhd, marhm, marht, marhw, marhyp, mig, mil, mlpa, mlpb, mlpcd, mlpe, mlpfg, mlph, mlpi, mlpj, mlpk, nwab, nwav, nwla, nwlk, nwre, oip, pap, relp, retp, sch, schg, schl, semp, sex, ssip, ssp, wagp, wkhp, wkl, wkw, wrk, yoep, anc, anc1p, anc2p, decade, dis, drivesp, esp, esr, fod1p, fod2p, hicov, hisp, indp, jwap, jwdp, lanp, migpuma, migsp, msp, naicsp, nativity, nop, oc, ...]
Index: []

[0 rows x 286 columns]

In [15]:
#explore table columns/keys of pums_2017

QUERY = """
    SELECT *
    FROM pums_2017 p
    WHERE p.rt = 'p'
    """
    
print("".join(['\033[1m', 'pums_2017', '\033[0m']))#make column name bold
print(pd.read_sql(QUERY, conn))

pums_2017
Empty DataFrame
Columns: [rt, serialno, division, sporder, puma, region, st, adjinc, pwgtp, agep, cit, citwp, cow, ddrs, dear, deye, dout, dphy, drat, dratx, drem, eng, fer, gcl, gcm, gcr, hins1, hins2, hins3, hins4, hins5, hins6, hins7, intp, jwmnp, jwrip, jwtr, lanx, mar, marhd, marhm, marht, marhw, marhyp, mig, mil, mlpa, mlpb, mlpcd, mlpe, mlpfg, mlph, mlpi, mlpj, mlpk, nwab, nwav, nwla, nwlk, nwre, oip, pap, relp, retp, sch, schg, schl, semp, sex, ssip, ssp, wagp, wkhp, wkl, wkw, wrk, yoep, anc, anc1p, anc2p, decade, dis, drivesp, esp, esr, fod1p, fod2p, hicov, hisp, indp, jwap, jwdp, lanp, migpuma, migsp, msp, naicsp, nativity, nop, oc, ...]
Index: []

[0 rows x 286 columns]

In [29]:
#explore table columns/keys of puma_names_2010
table = 'puma_names_2010'

QUERY = f"""
    SELECT *
    FROM {table} p
    WHERE p.state_fips LIKE '053'
    """
    
print("".join(['\033[1m', f'{table}', '\033[0m']))#make column name bold
print(pd.read_sql(QUERY, conn))

puma_names_2010
Empty DataFrame
Columns: [state_fips, state_name, cpuma0010, puma, geoid, gisjoin, puma_name]
Index: []

In [70]:
QUERY = """
    SELECT *
    FROM pums_2017 ps
    JOIN puma_names_2010 pn
    ON ps.puma = pn.puma
    WHERE pn.puma SIMILAR TO '1161(0|1|2|3|4|5)'
    AND ps.agep >= 16
    AND ps.agep <= 24
    AND ps.sch = '1'
    AND ps.dis = '2'
    AND ps.esr SIMILAR TO '%(3|6)%'
    ORDER BY pn
    """
db_south = pd.read_sql(QUERY, conn)
db_south

,rt,serialno,division,sporder,puma,region,st,adjinc,pwgtp,agep,...,pwgtp78,pwgtp79,pwgtp80,state_fips,state_name,cpuma0010,puma,geoid,gisjoin,puma_name
0,P,2013000550228,9,03,11610,4,53,1061971,58.0,21.0,...,49.0,94.0,97.0,53,Washington ...,1044,11610,5311610,G53011610,"King County (Central)--Renton City, Fairwood, ..."
1,P,2014000753355,9,03,11610,4,53,1045195,22.0,21.0,...,8.0,25.0,8.0,53,Washington ...,1044,11610,5311610,G53011610,"King County (Central)--Renton City, Fairwood, ..."
2,P,2013001103945,9,06,11610,4,53,1061971,27.0,22.0,...,29.0,8.0,28.0,53,Washington ...,1044,11610,5311610,G53011610,"King County (Central)--Renton City, Fairwood, ..."
3,P,2013000111689,9,05,11610,4,53,1061971,40.0,19.0,...,52.0,32.0,36.0,53,Washington ...,1044,11610,5311610,G53011610,"King County (Central)--Renton City, Fairwood, ..."
4,P,2013000550228,9,02,11610,4,53,1061971,59.0,21.0,...,50.0,95.0,96.0,53,Washington ...,1044,11610,5311610,G53011610,"King County (Central)--Renton City, Fairwood, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,P,2017000751960,9,02,11612,4,53,1011189,54.0,22.0,...,71.0,58.0,16.0,53,Washington ...,1046,11612,5311612,G53011612,"King County (Far Southwest)--Federal Way, Des ..."
318,P,2015000664648,9,03,11612,4,53,1035988,20.0,19.0,...,26.0,17.0,18.0,53,Washington ...,1046,11612,5311612,G53011612,"King County (Far Southwest)--Federal Way, Des ..."
319,P,2015001030849,9,02,11612,4,53,1035988,47.0,22.0,...,52.0,73.0,14.0,53,Washington ...,1046,11612,5311612,G53011612,"King County (Far Southwest)--Federal Way, Des ..."
320,P,2014001475081,9,04,11612,4,53,1045195,13.0,22.0,...,12.0,12.0,5.0,53,Washington ...,1046,11612,5311612,G53011612,"King County (Far Southwest)--Federal Way, Des ..."
321,P,2017000360750,9,02,11612,4,53,1011189,77.0,18.0,...,30.0,97.0,69.0,53,Washington ...,1046,11612,5311612,G53011612,"King County (Far Southwest)--Federal Way, Des ..."

In [71]:
sum(db_south['pwgtp'])

8946.0

In [ ]:
# conn.close()